# Generated by Django 4.2.4 on 2023-09-24 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='itemDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('age', models.IntegerField()),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=100, null=True)),
                ('qualifications', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(blank=True, default='static/images/Image 13.jpg', null=True, upload_to='image/')),
            ],
        ),
    ]
